log: debug
flask:
  host: 127.0.0.1
  port: 5050
channel_service:
  api_base: http://127.0.0.1:6001
  timeout: 300
ollama:
  api_base: http://localhost:11434
  model: gpt-oss:120b
  timeout: 300
  temperature: 0.1
  blacklist:
    - glm-ocr:latest
    - laguna-xs.2:bf16
    - qwen3-vl:30b
    - glm-4.7-flash:bf16
    - qwen3.5:0.8b
    - llama4:latest
    - qwen3.5:2b
    - qwen3.5:4b
    - mistral-nemo:12b-instruct-2407-fp16
    - qwen3.5:9b
    - qwen2.5vl:latest
    - nemotron3:33b
    - qwen3-coder:latest
